# -*- coding: utf-8 -*-
"""DataVisaulization.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1iEPqFZoBGg4B88Hyf2gFtyMYpzrBVxk5
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/alura-cursos/bibliotecas_visualizacao/refs/heads/main/Dados/imigrantes_canada.csv')

df

df.info()

df.set_index('País', inplace = True)

df

anos = list(map(str, range(1980, 2014)))
anos

brasil = df.loc["Brasil", anos]
brasil

brasil_dict = {'ano': brasil.index.tolist(), 'imigrantes': brasil.values.tolist()}
dados_brasil = pd.DataFrame(brasil_dict)

dados_brasil

import matplotlib.pyplot as plt

plt.figure(figsize=(10,4))
plt.plot(dados_brasil['ano'],dados_brasil['imigrantes'])
plt.xticks(['1980', '1985', '1990', '1995', '2000', '2005', '2010'])
plt.yticks([500, 1000, 1500, 2000, 2500, 3000])
plt.title('Imigração do Brasil para o Canada')
plt.xlabel('Ano')
plt.ylabel('Imigrantes')
plt.show()

df_comparacao = df.loc[['Brasil', 'Argentina'], anos]
df_comparacao = df_comparacao.T
df_comparacao.head()

plt.figure(figsize=(10,4))
plt.plot(df_comparacao['Brasil'],label = 'Brasil')
plt.plot(df_comparacao['Argentina'],label ='Argentina')
plt.title('Imigração do Brasil e Argentina para o Canadá')
plt.xlabel('Ano')
plt.ylabel('Número de imigrantes')
plt.xticks(['1980', '1985', '1990', '1995', '2000', '2005', '2010'])
plt.yticks([500, 1000, 1500, 2000, 2500, 3000])
plt.legend()
plt.show()

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(dados_brasil['ano'],dados_brasil['imigrantes'])
ax.set_title('Imigração do Brasil para o Canadá\n1980 a 2013')
ax.set_xlabel('Ano')
ax.set_ylabel('Imigrantes')
ax.xaxis.set_major_locator(plt.MultipleLocator(5))
plt.show()

fig,  axs = plt.subplots(1, 2, figsize=(15,5))

axs[0].plot(dados_brasil['ano'], dados_brasil['imigrantes'])
axs[0].set_title('Imigração do Brasil para o Canadá\n1980 a 2013')
axs[0].set_xlabel('Ano')
axs[0].set_ylabel('Numero de Imigrantes')
axs[0].xaxis.set_major_locator(plt.MultipleLocator(5))
axs[0].grid()


axs[1].boxplot(dados_brasil['imigrantes'])
axs[1].set_title('Boxplot da migração do Brasil para o Canadá\n1980 a 2013')
axs[1].set_xlabel('Brasil')
axs[1].set_ylabel('Número de Imigrantes')
axs[1].grid()

plt.show()

dados_brasil.describe()

fig, axs = plt.subplots(2,2, figsize=(10,6))
fig.subplots_adjust(hspace=0.5, wspace=0.3)
fig.suptitle('Imigração dos quatro maiores países da América do Sul para o Canadá de 1980 a 2013')

axs[0,0].plot(df.loc['Brasil', anos])
axs[0,0].set_title('Brasil')

axs[0,1].plot(df.loc['Colômbia', anos])
axs[0,1].set_title('Colômbia')

axs[1,0].plot(df.loc['Argentina', anos])
axs[1,0].set_title('Argentina')

axs[1,1].plot(df.loc['Peru', anos])
axs[1,1].set_title('Peru')

for ax in axs.flat:
  ax.xaxis.set_major_locator(plt.MultipleLocator(5))

for ax in axs.flat:
  ax.set_xlabel('Ano')
  ax.set_ylabel('Número de imigrantes')

ymin = 0
ymax = 7000

for ax in axs.ravel():
  ax.set_ylim(ymin, ymax)

plt.show()

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(dados_brasil['ano'],dados_brasil['imigrantes'], lw = 3, marker = 'o', color ='g')
ax.set_title('Imigração do Brasil para o Canadá\n1980 a 2013', fontsize = 18, loc = 'left')
ax.set_xlabel('Ano', fontsize = 14)
ax.set_ylabel('Imigrantes', fontsize = 14)
ax.xaxis.set_tick_params(labelsize = 12)
ax.yaxis.set_tick_params(labelsize = 12)
ax.xaxis.set_major_locator(plt.MultipleLocator(5))
plt.grid(linestyle='--')
plt.show()

df.head()

america_sul = df.query('Região == "América do Sul"')
america_sul

cores = ['royalblue', 'orange',
         'forestgreen', 'orchid',
         'purple', 'brown',
         'slateblue', 'gray',
         'olive', 'navy',
         'teal', 'tomato']

fig, ax = plt.subplots(figsize=(12, 5))
ax.bar(america_sul.index, america_sul['Total'], color=cores)
ax.set_title('Imigração da América do Sul para o Canadá\n1980 a 2013', loc='left', fontsize=18)
ax.set_ylabel('Número de imigrantes', fontsize=14)
ax.set_xlabel('')
ax.yaxis.set_tick_params(labelsize=12)
ax.xaxis.set_tick_params(labelsize=12)

plt.show()

# A PRESENÇA DO "H" NO "BARH" COLOCA O GRAFICO NA HORIZONTAL, E ALÉM DISSO É IMPORTANTE MUDAR O NOME DAS LABELS, POIS OS EIXOS X E Y SE INVERTEM.
cores = ['royalblue', 'orange',
         'forestgreen', 'orchid',
         'purple', 'brown',
         'slateblue', 'gray',
         'olive', 'navy',
         'teal', 'tomato']

fig, ax = plt.subplots(figsize=(12, 5))
ax.barh(america_sul_sorted.index, america_sul_sorted['Total'], color=cores)
ax.set_title('Imigração da América do Sul para o Canadá\n1980 a 2013', loc='left', fontsize=18)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('')
ax.yaxis.set_tick_params(labelsize=12)
ax.xaxis.set_tick_params(labelsize=12)



plt.show()

# FOI CRIADA UM NOVO DATAFRAME PARA ORGANIZAR OS DADOS NO ORDEM MENOR PARA MAIOR (america_sul_sorted), O NOME DO DATAFRAME TBM FOI SUBSTITUIDO À CIMA
america_sul_sorted = america_sul.sort_values('Total', ascending = True )

# OUTRO BLOCO DE CODIGO COM O MESMO RESULTADO DO ACIMA, PORÉM NESSE O BRASIL SERÁ DESTACADO
cores = []
for pais in america_sul_sorted.index:
    if pais == 'Brasil':
     cores.append('green')
    else:
     cores.append('silver')


fig, ax = plt.subplots(figsize=(14, 5))
ax.barh(america_sul_sorted.index, america_sul_sorted['Total'], color=cores)
ax.set_title('Imigração da América do Sul para o Canadá\n1980 a 2013 (Brasil foi o 4º maior imigrante)', loc='left', fontsize=18)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('')
ax.yaxis.set_tick_params(labelsize=12)
ax.xaxis.set_tick_params(labelsize=12)

# ADICIONANDO OS VALORES TOTAIS AO LADO DAS BARRAS PARA MELHORAR O ENTENDIMENTO
for i, v in enumerate(america_sul_sorted['Total']):
    ax.text(v + 20, i, str(v), color='black', fontsize=10, ha='left', va='center')

ax.set_frame_on(False)
ax.get_xaxis().set_visible(False)
ax.tick_params(axis='both', which='both', length=0)

fig.savefig('imigracao_america_sul.png', transparent=False, dpi=300, bbox_inches='tight')

plt.show()

print(fig.canvas.get_supported_filetypes())

fig, ax = plt.subplots(figsize=(10,4))
ax.plot(dados_brasil['ano'],dados_brasil['imigrantes'], lw = 3, marker = 'o', color ='g')
ax.set_title('Imigração do Brasil para o Canadá\n1980 a 2013', fontsize = 18, loc = 'left')
ax.set_xlabel('Ano', fontsize = 14)
ax.set_ylabel('Imigrantes', fontsize = 14)
ax.xaxis.set_tick_params(labelsize = 12)
ax.yaxis.set_tick_params(labelsize = 12)
ax.xaxis.set_major_locator(plt.MultipleLocator(5))
ax.spines['top'].set_visible(False)
ax.spines['right'].set_visible(False)
fig.savefig('imigracao_brasil_canada.png', transparent=False, dpi=300, bbox_inches='tight')
plt.show()

import seaborn as sns

sns.set_theme()

top_10= df.sort_values('Total', ascending = False).head(10)

top_10

sns.barplot(data=top_10, x=top_10.index, y='Total',palette = "mako", hue = top_10.index)

sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette = "mako", hue = top_10.index)

ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h',palette = "icefire", hue = top_10.index)

ax.set(title="Países com maior imigração para o Canadá\n1980 a 2013",
       xlabel='Número de Imigrantes',
        ylabel='')

plt.show()

fig, ax = plt.subplots(figsize=(8, 4))

ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h',palette = "icefire", hue = top_10.index)

ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=16)
ax.set_xlabel('Número de imigrantes', fontsize=14)
ax.set_ylabel('', fontsize=14)

plt.show()

# OUTRO MÉTODO PARA PASSAR PALETAS DE CORES PARA GRAFICOS (def gerar_grafico_paleta(palette):)
def gerar_grafico_paleta(palette):
    fig, ax = plt.subplots(figsize=(8,4))
    ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette=palette)
    ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=18)
    ax.set_xlabel('Número de imigrantes', fontsize=14)
    ax.set_ylabel('')
    plt.show()

gerar_grafico_paleta('Blues')

# CORES NA ORDEM REVERSA
gerar_grafico_paleta('Blues_r')

gerar_grafico_paleta('rocket')

gerar_grafico_paleta('coolwarm')

gerar_grafico_paleta("tab10")

sns.set_theme(style='dark')
gerar_grafico_paleta("tab10")

sns.set_theme(style='whitegrid')
gerar_grafico_paleta("tab10")

sns.set_theme(style='white')
gerar_grafico_paleta("tab10")

sns.set_theme(style='ticks')
gerar_grafico_paleta("tab10")

fig, ax = plt.subplots(figsize=(8, 4))
ax = sns.barplot(data=top_10, y=top_10.index, x='Total', orient='h', palette='tab10')

ax.set_title('Países com maior imigração para o Canadá\n1980 a 2013', loc='left', fontsize=18)
ax.set_xlabel('Número de Imigrantes', fontsize=14)
ax.set_ylabel('')
sns.despine()

plt.show()

sns.set_theme()
sns.set_palette('Dark2')

fig, ax = plt.subplots(figsize=(10, 5))
ax = sns.lineplot(df.loc['Brasil', anos], label='Brasil', lw=3)
ax = sns.lineplot(df.loc['Argentina', anos], label='Argentina', lw=3)
ax = sns.lineplot(df.loc['Peru', anos], label='Peru', lw=3)
ax = sns.lineplot(df.loc['Colômbia', anos], label='Colômbia', lw=3)

ax.set_title('Imigração dos maiores países da América do Sul\npara o Canadá de 1980 a 2013', loc='left', fontsize=20)
ax.set_xlabel('Ano', fontsize=14)
ax.set_ylabel('Número de imigrantes', fontsize=14)

ax.xaxis.set_major_locator(plt.MultipleLocator(5))

ax.legend(title='Países', loc='upper right', bbox_to_anchor=(1.18, 1.02))

plt.show()

import plotly.express as px

fig = px.line(dados_brasil, x= 'ano', y= 'imigrantes', title= 'Imigração do Brasil para o Canadá no periodo de 1980 a 2013')
fig.update_traces(line_color= 'green',line_width= 4)
fig.update_layout(width= 1000, height= 500, xaxis= {'tickangle': -45},
                  font_family= 'Arial',
                  font_size= 14,
                  font_color= 'gray',
                  title_font_color= 'black',
                  title_font_size= 22,
                  xaxis_title= 'Ano',
                  yaxis_title= 'Número de Imigrantes')
fig.show()

america_sul.head()

df_america_sul_clean= america_sul.drop(['Continente', 'Região', 'Total'],axis= 1)
america_sul_final = df_america_sul_clean.T

america_sul_final.head()

fig = px.line(america_sul_final,
              x= america_sul_final.index,
              y= america_sul_final.columns,
              color= 'País',
              title= 'Imigração da América do Sul para o Canadá de 1980 a 2013',
              markers= True)
fig.update_layout(xaxis= {'tickangle': -45},
                  xaxis_title= 'Anos',
                  yaxis_title= 'Número de Imigrantes')
fig.show()

fig.write_html('imigração_america_sul.html')

dados_brasil['ano'] = dados_brasil['ano'].astype(int)

import plotly.graph_objs as go

fig = go.Figure()

fig.add_trace(
    go.Scatter(x=[dados_brasil['ano'].iloc[0]], y=[dados_brasil['imigrantes'].iloc[0]], mode='lines', name='Imigrantes', line=dict(width=4))
)

import plotly.graph_objs as go

# Criando uma figura
fig = go.Figure()

# Adicionando a linha do gráfico e definindo a espessura da linha
fig.add_trace(
    go.Scatter(x=[dados_brasil['ano'].iloc[0]], y=[dados_brasil['imigrantes'].iloc[0]], mode='lines', name='Imigrantes', line=dict(width=4))
)

# Definindo as configurações de layout
fig.update_layout(
    title=dict(
        text='<b>Imigração do Brasil para o Canadá no período de 1980 a 2013</b>',
        x=0.12,
        xanchor='left',
        font=dict(size=20)
    ),
    xaxis=dict(range=[1980, 2013], autorange=False, title='<b>Ano</b>'),
    yaxis=dict(range=[0, 3000], autorange=False, title='<b>Número de imigrantes</b>'),
    updatemenus=[dict(
        type='buttons',
        showactive=False,
        buttons=[dict(
            label='Play',
            method='animate',
            args=[None, {'frame': {'duration': 100, 'redraw': True}, 'fromcurrent': True}]
        )]
    )],
    width=1000,
    height=500
)

# Definir as configurações de animação
frames = [go.Frame(data=[go.Scatter(x=dados_brasil['ano'].iloc[:i+1], y=dados_brasil['imigrantes'].iloc[:i+1])]) for i in range(len(dados_brasil))]
fig.frames = frames

# Mostrando a figura
fig.show()

fig.write_html('imigração_america_sul_animada.html')

# MESMO PROCESSO PARA CRIAR UM DATAFRAME CONTENDO OS DADOS RELACIONADOS AO BRASIL, SÓ Q PARA A ARGENTINA
argentina = df.loc["Argentina", anos]
argentina

# MESMO PROCESSO PARA CRIAR UM DATAFRAME CONTENDO OS DADOS RELACIONADOS AO BRASIL, SÓ Q PARA A ARGENTINA (dados_argentina)
argentina_dict = {'ano': argentina.index.tolist(), 'imigrantes': argentina.values.tolist()}
dados_argentina = pd.DataFrame(argentina_dict)

import plotly.graph_objs as go

# Criando uma figura
fig = go.Figure()

# Adicionando a linha com os dados do Brasil
fig.add_trace(
    go.Scatter(x=[dados_brasil['ano'].iloc[0]], y=[dados_brasil['imigrantes'].iloc[0]], mode='lines', name='Imigrantes do Brasil', line=dict(width=4))
)

# Adicionando a linha com os dados da Argentina
fig.add_trace(
    go.Scatter(x=[dados_argentina['ano'].iloc[0]], y=[dados_argentina['imigrantes'].iloc[0]], mode='lines', name='Imigrantes da Argentina', line=dict(width=4))
)

# Definindo as configurações de layout
fig.update_layout(
    title=dict(
        text='<b>Imigração do Brasil e da Argentina para o Canadá no período de 1980 a 2013',
        x=0.1,

        font=dict(size=18)
    ),
    xaxis=dict(range=[1980, 2013], autorange=False, title='<b>Ano</b>'),
    yaxis=dict(range=[0, 3000], autorange=False, title='<b>Número de imigrantes</b>'),
    updatemenus=[dict(
        type='buttons',
        showactive=False,
        buttons=[dict(
            label='Play',
            method='animate',
            args=[None, {'frame': {'duration': 100, 'redraw': True}, 'fromcurrent': True}]
        )]
    )],
    width=1200, # largura da figura em pixels
    height=600 # altura da figura em pixels
)

# Definindo as configurações de animação
frames = []
for i in range(len(dados_brasil)):
    frame_data = [
        go.Scatter(x=dados_brasil['ano'].iloc[:i+1], y=dados_brasil['imigrantes'].iloc[:i+1]),
        go.Scatter(x=dados_argentina['ano'].iloc[:i+1], y=dados_argentina['imigrantes'].iloc[:i+1])
    ]
    frame = go.Frame(data=frame_data)
    frames.append(frame)
fig.frames = frames

# Mostrando a figura
fig.show()

fig.write_html('imigração_brasil_argentina_animado.html')

