# -*- coding: utf-8 -*-
"""Projeto_Python_Data_Science(RESOLVIDO).ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1J26uaG71MLgkBlLsv3jCWHgt0AcEq4SE

# Python para Data Science

Notebook para o curso de Python para Data Science publicado na plataforma da [Alura](https://www.alura.com.br/)

# Introdução ao Python

Vamos conhecer o Python, nosso ambiente de estudo e também faremos nosso primeiro código nessa linguagem!

## Google Colaboratory

Já aprendemos o que é o [Python](https://www.python.org/) agora vamos aprender a utilzar o [Google Colaboratory](https://colab.research.google.com/) e programar em um notebook.

Vamos testar algumas funções dessa ferramenta.

**`>>> Use essa célula para mover <<<`**
"""



"""## Olá mundo!

Vamso conhecer mais como funciona o ambiente interativo de um notebook. Para isso vamos executar nosso primeiro comando em Python: [`print()`](https://docs.python.org/3/library/functions.html#print)
"""

print('Olá Mundo!')

print(10)

print('Pedro', 18)

print('Escola de Dados Alura')

print('Escola de Dados Alura')

"""# Manipulando dados

Vamos aprender sobre as variáveis no python, como elas são declaradas e utilizadas além de conhecer outros comandos dentro do Python. :D

## Variáveis

Em Data Science nós trabalhamos com vários dados e informações, então é essencial saber trabalhar com variáveis.

Criamos uma variável no python através da atribuição de um valor a ela.

Para fazer isso, colocamos o nome da variável um sinal de igual (`=`) e o valor que queremos atribuir
"""

idade = 18

print(idade)

idade = 21
print(idade)

idade = 23
idade

nome = 'Pedro'
nome

"""Nomes que **não** podemos definir para variáveis:

- **Nomes que começam com números**
  - Exemplos: `10_notas`, `2_nomes_casa`, etc.
- **Palavras separada por espaço**
  - Exemplos: `Nome escola`, `notas estudantes`, etc.
- **Nomes de funções do Python**
  - Exemplos: `print`, `type`, etc.

> Letras maiúsculas e minúsculas vão gerar diferentes variáveis. A varíavel `idade` é diferente de `Idade` que por sua vez também é diferente de `IDADE`:
``` Python
idade = 1
Idade = 2
IDADE = 3
_idade = 4
_idade_ = 5
print(idade, Idade, IDADE, _idade, _idade_)
1 2 3 4 5
```

## Tipos de variáveis

Cada variável contém uma classe especifica quanto ao tipo de objeto que ela está se referenciando. Essas classes vão ser diferentes a partir do tipo de dado que nós atribuimos a uma variável.

Para saber a classe de cada elemento usamos a função [`type()`](https://docs.python.org/3/library/functions.html#type)
"""

i = 24
type(i)

f = 45.9
type(f)

s = 'Pedro 3456'
type(s)

b = False
type(b)

"""Em um conjunto de dados escolares podemos ter vários tipos de informações. Digamos que tenhamos acesso à ficha de dados do aluno *Frabicio Daniel* como transformamos ela em variáveis no Python?

#### Ficha:

- Nome: Fabricio Daniel
- Idade: 15 anos
- Media do semestre: 8,45
- Situação de aprovação: Verdadeira (aprovado)
"""

nomeAluno = "Fabricio Daniel"
idadeAluno = 15
mediaAluno = 8.45
situacaoAluno = True
print(nomeAluno)
print(idadeAluno)
print(mediaAluno)
print(situacaoAluno)

"""## Variáveis numéricas

Entre os tipos de dados numéricos vamos nos focar no tipo `inteiro` e `float`.

Temos uma tabela de informação de empregos quanto ao cargo, quantidade de pessoas empregadas e o salário correspondente:

|Cargo | Quantidade | Salário|
|---|---|---|
|Segurança | 5 | 3000 |
|Docente | 16| 6000|
|Diretoria| 1 |12500|

Precisamos trabalhar com esses dados fornecendo:

- A quantidade total de empregados;
- A diferença entre o salário mais baixo e mais alto; e
- A média ponderada da faixa salarial da escola.
"""

q_seguranca = 5
s_seguranca = 3000

q_docente = 16
s_docente = 6000

q_diretoria = 1
s_diretoria = 12500

qtdEmpregados = q_seguranca + q_docente + q_diretoria
qtdEmpregados

diferencaSalarial = s_diretoria - s_seguranca
diferencaSalarial

pesoSeguranca = q_seguranca * s_seguranca
pesoDocente = q_docente * s_docente
pesoDiretoria = q_diretoria * s_diretoria
mediaPonderada = (pesoSeguranca + pesoDocente + pesoDiretoria)/qtdEmpregados
mediaPonderada

"""## Strings

Strings são caracterizada por ter um conjunto de caracteres formando um texto.

Strigs podem ser criadas ao atribuirmos a uma variável um dado que esteja entre aspas simples (`'`) ou aspas duplas (`"`)
"""

s1 = 'Alura'
s2 = "Alura"
print(type(s1),type(s2))

"""As variáveis textuais contém vários métodos que nos ajudam a formatar strings. Métódos podem ser executados ao definirmos um objeto seguindo a seguinte estrutura:

```
objeto.metodo()
```

Existem métodos que não necessitam dos `()`, é preciso verificar a documentação de cada caso.

---
**Situação:**

Recebemos uma variável com o nome de uma professora da escola para inserimos no cadastro. No entanto, precisamos tratar esse texto antes de inserirmos no sistema
"""

texto = '  Geovana Alessandra dias Sanyos '

"""O objetivo final é que o nome esteja da seguinte forma:

```
'GEOVANA ALESSANDRA DIAS SANTOS'
```

### [`str.upper()` ](https://docs.python.org/3/library/stdtypes.html#str.upper)
Converte uma string para maiúsculas
"""

texto.upper()

"""### [`str.lower()`](https://docs.python.org/3/library/stdtypes.html#str.lower)
Método converte uma string para minúsculas.
"""

texto.lower()

"""### [`str.strip()`](https://docs.python.org/3/library/stdtypes.html#str.strip)
Método remove os espaços em branco do início e do fim de uma string.
"""

texto.strip()

"""### [`str.replace(antigo, novo)`](https://docs.python.org/3/library/stdtypes.html#str.replace)

Método substitui todas as ocorrências do texto "antigo" na string por "novo"
"""

texto.replace('y', 't')

"""### Observações

1. Os métodos retornam uma **tranformação**, não a executam no texto!

2. Além disso, podemos acumular a execução de métodos.
"""

texto

"""Para que seja executada a transformação nós podemos atribuir às saídas das transformações à variável"""

texto = texto.strip().upper().replace('y', 't')
texto

"""## Coletando dados

Em algumas aplicações precisamos coletar valores da pessoa usuária do nosso projeto. Em python conseguimos coletar dados de usuário através do comando [`input()`](https://docs.python.org/3/library/functions.html#input).

Para fazer essa coleta podemos atribuir essa função à uma variável.
"""

nome = input("Digite seu nome: ")

nome

"""O retorno desse comando sempre será uma *string*. Isso quer dizer que mesmo que façamos uma coleta de algo que deva ser numérico, ele será uma string.

Então, será preciso **converter o resultado caso não seja desejável obter uma string**.

Existem funções para conversão de valores:

- Inteiros: [`int(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#int)
- Float: [`float(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#float)
- String: [`str(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#func-str)
- Booleano: [`bool(dado_para_conversao)`](https://docs.python.org/3/library/functions.html#bool)
"""

ano_entrada = input('Escreva o ano de ingresso do(a) estudante: ')

type(ano_entrada)

ano_entrada = int(input('Escreva o ano de ingresso do(a) estudante: '))

type(ano_entrada)

"""Buscaremos apresentar melhor agora o resultado que obtivemos da transformação. Nós conseguimos formatar e apresentar o nosso resultado misturando strings com valores não textuais.

Para fazer isso usamos a estrutura de formatação `f` com strings.
"""

nota_entrada = float(input('Digite a nota do teste de ingresso: '))
print(f'Ano de entrada {ano_entrada} - nota do teste de ingresso {nota_entrada}')

"""# Estruturas condicionais

## `IF` e `ELSE`

O `if` e `else` são duas estruturas condicionais. O `if` executará o bloco de comando caso a condição colocada for **verdadeira**. O `else` é um caso em que a condicional de `if` seja **falsa**.

O `if` é uma palavra-chave em Python que significa "se". Ele é usado para formar uma estrutura condicional, que permite que você verifique se uma determinada condição é verdadeira ou falsa e, em seguida, execute um bloco de código específico dependendo do resultado da verificação. A sintaxe para usar o `if` é:



```
if condição:
    # faça algo
```
"""

if 2>7:
  print('condiçaõ verdaeira')
print('fora do bloco')

"""Já o `else` em Python é usada em conjunto com a palavra-chave `if` para formar uma estrutura condicional. A sintaxe para usar o `else` é:

```
if condição:
  # código caso seja verdade
else:
  # código caso seja falso
```

O `else` é executado quando a condição verificada pelo `if` é avaliada como `False`.

---
**Situação:**

Receberemos a média de estudantes e precisamos de um algoritmo que execute a análise e decida se esse estudante está **Aprovado** ou Reprovado, mostrando uma mensagem do resultado. Para ser aprovado, a média precisa ser igual ou superior à 6.0.
"""

media = float(input('Digite a média: '))
if media >= 6.0:
  print('Aprovado')
else:
  print('Reprovado')

"""Agora a nossa instituição de ensino lançou uma nota oficial que pessoas que tenham média entre 4.0 e 6.0 podem fazer os cursos de **Recuperação** nas férias para poder recuperar a nota.

Então podemos agora fazer um conjunto de `if`s para que possamos estruturar essa nova condição.
"""

media = float(input('Digite a média: '))

if media >= 6.0:
  print('Aprovado(a)')
if 6.0 > media >= 4.0:
  print('Recuperação')
if media < 4.0:
  print('Reprovado(a)')

"""Notemos que em casos com 3 situações como esse precisamos definir bem nossas condições. Pois foi feita uma construção com `else` no final, ele irá considerar apenas a alguma condicional para ser o caso **falso** podendo resultar em duas (ou mais) execuções.

Por exemplo:
"""

media = float(input('Digite a média: '))

if media >= 6.0:
  print('Aprovado(a)')
if 6.0 > media >= 4.0:
  print('Recuperação')
else:
  print('Reprovado(a)')

media = float(input('Digite a média: '))

if media >=6.0:
  print('Aprovado')
else:
  if media >= 4.0:
    print('Recuperação')
  else:
    print('Reprovado')

"""## `ELIF`

O `elif` é uma palavra-chave em Python que significa "senão, se" e pode ser considerado uma união do `else` com um `if`. Ela é usada em conjunto com a palavra-chave `if` para formar uma estrutura condicional encadeada.

A sintaxe para usar o `elif` é:

```
if condição1:
    # faça algo
elif condição2:
    # faça outra coisa
elif condição3:
    # faça mais alguma coisa
else:
    # faça algo diferente
```

O `elif` permite que você verifique várias condições de forma encadeada, economizando espaço em seu código. Se a primeira condição for avaliada como `False`, o interpretador Python avaliará a próxima condição no `elif`. Isso continuará até que uma condição seja avaliada como `True` ou até que o `else` seja atingido. Se nenhuma das condições forem avaliadas como `True`, a execução do código do `else` será iniciada.

Vamos usar o mesmo caso anterior:
"""

media = float(input('Digite a média: '))
if media >= 6.0:
  print('Aprovado')
elif media >= 4.0:
  print('Recuperação')
else:
  print('Reprovado')

"""## Operadores

Durante a construção de comandos por vezes precisamos de uma elaboração maior de da expressão condicional, necessitando que alguns operadores lógicos estejam integrados.

### `AND`, `OR`, `NOT`

Os operadores lógicos `and`, `or` e `not` são usados para combinar expressões lógicas em Python. Eles são usados frequentemente em conjunto com o `if` para criar estruturas condicionais mais complexas.

- `AND` é usado para verificar se duas condições são verdadeiras. A expressão lógica¹ `x and y` é avaliada como `True` apenas se **ambas as condições `x` e `y` forem verdadeiras**, e como `False` caso contrário.

- `OR` é usado para verificar se pelo menos uma das condições é verdadeira. A expressão lógica `x or y` é avaliada como `True` **se pelo menos uma das condições `x` ou `y` for verdadeira**, e como `False` se ambas forem falsas.

- `NOT` é usado para **negar uma condição**. A expressão lógica not x é avaliada como True se a condição x for falsa, e como False se a condição x for verdadeira.

¹ Uma expressão lógica é uma declaração que pode ser avaliada como verdadeira ou falsa. Ela é composta por operandos lógicos² e operadores lógicos³, que são usados ​​para combinar várias expressões lógicas em uma única expressão.

² Os operandos lógicos são os elementos que são comparados ou avaliados em uma expressão lógica. Eles são geralmente valores verdadeiros ou falsos, mas também podem ser expressões lógicas mais complexas. Em Python, os operandos lógicos são os valores `True` e `False`.

³ Os operadores lógicos são os símbolos ou palavras-chave que são usados ​​para combinar várias expressões lógicas em uma única expressão. Em Python, os operadores lógicos são `and`, `or` e `not`, bem como as palavras-chave `if`, `elif` e `else`.
"""

t1 = t2 = True
f1 = f2 = False

if t1 and t2:
  print('expressão verdadeira')
else:
  print('expressão falsa')

if f1 or t1 :
  print('expressão verdadeira')
else:
  print('expressão falsa')

if not t1 :
  print('expressão verdadeira')
else:
  print('expressão falsa')

"""### `IN`

É usado para verificar se um elemento está presente em uma lista, tupla ou outra variável de conjunto. A expressão `x in y` é avaliada como `True` se o elemento `x` estiver presente na variável de conjunto `y`, e como `False` caso contrário.

Podemos verificar isso com variáveis de texto.

---

**Situação:**

Na escola foi passada uma lista com nomes de estudantes que foram aprovados por média no semestre, mas é preciso verificar se alguns nomes estão nessa lista para verificar se os dados estão corretos.

A lista distribuida pode ser observada abaixo:

```
lista = 'José da Silva, Maria Oliveira, Pedro Martins, Ana Souza, Carlos Rodrigues, Juliana Santos, Bruno Gomes, Beatriz Costa, Felipe Almeida, Mariana Fernandes, João Pinto, Luísa Nascimento, Gabriel Souza, Manuela Santos, Thiago Oliveira, Sofia Ferreira, Rafael Albuquerque, Isabella Gomes, Bruno Costa, Maria Martins, Rafaela Souza, Matheus Fernandes, Luísa Almeida, Beatriz Pinto, Mariana Rodrigues, Gabriel Nascimento, João Ferreira, Maria Albuquerque, Felipe Oliveira
'
```

Os nomes que precisam ser verificados são os seguintes:

```
nome_1 = 'Mariana Rodrigues'
nome_2 = 'Marcelo Nogueira'
```
"""

lista = 'José da Silva, Maria Oliveira, Pedro Martins, Ana Souza, Carlos Rodrigues, Juliana Santos, Bruno Gomes, Beatriz Costa, Felipe Almeida, Mariana Fernandes, João Pinto, Luísa Nascimento, Gabriel Souza, Manuela Santos, Thiago Oliveira, Sofia Ferreira, Rafael Albuquerque, Isabella Gomes, Bruno Costa, Maria Martins, Rafaela Souza, Matheus Fernandes, Luísa Almeida, Beatriz Pinto, Mariana Rodrigues, Gabriel Nascimento, João Ferreira, Maria Albuquerque, Felipe Oliveira'
lista

nome_1 = 'Mariana Rodrigues'
nome_2 = 'Marcelo Nogueira'

if nome_1 in lista:
  print(f'{nome_1} está na lista')
else:
  print(f'{nome_1} não está na lista')

if nome_2 in lista:
  print(f'{nome_2} está na lista')
else:
  print(f'{nome_2} não está na lista')

"""# Estruturas de repetição

Quando temos que executar um mesmo bloco de comandos por várias vezes não é muito interessante fazer isso à mão.

Imaginemos a situação de termos que coletar e imprimir a média de duas notas de **3 estudantes**:
"""

nota_1 = float(input('Digite a 1° nota: '))
nota_2 = float(input('Digite a 2° nota: '))

print(f'Média: {(nota_1+nota_2)/2}')

"""Agora imaginemos uma situação em que não são apenas 3 estudantes, mas sim 100 estudantes. Não seria interessante repetir o mesmo código por 100 vezes, mas sim **executar o mesmo código 100 vezes**.

Essa repetição conseguimos construir com laços de repetição!

## `WHILE`

O laço `while` é uma estrutura de controle de repetição em Python que permite executar um bloco de código repetidamente enquanto uma determinada condição é verdadeira. Sua estrutura é:



```
while condição:
    # bloco de código
```

Vamos construir um exemplo com um contador de 1 até 10.
"""

contador = 1
while contador <= 10:
  print(contador)
  contador += 1

"""Agora vamos coletar as notas e médias de cada aluno dentro do while. Faremos um exemplo com 3 médias."""

contador = 1
while contador <= 3:
  print(f"Aluno {contador}")
  nota_1 = float(input('Digite a 1° nota: '))
  nota_2 = float(input('Digite a 2° nota: '))

  print(f'Média: {(nota_1+nota_2)/2}')
  contador += 1

"""```
# Isto está formatado como código
```

## `FOR`

O laço `for` é um tipo de estrutura de controle de fluxo em Python que permite iterar sobre um conjunto de elementos. A sua estrutura é:



```
for elemento in conjunto:
    # código a ser executado para cada elemento
```

O laço for itera sobre cada elemento do conjunto especificado e executa o bloco de código dentro do laço para cada elemento. Quando o laço chega ao final do conjunto, ele é interrompido e o programa continua a execução após o laço.

O conjunto pode ser gerado com a função [`range()`](https://docs.python.org/3/library/functions.html#func-range). Que é uma função capaz de gerar uma sequência de números inteiros. A estrutura dessa função é:

```
range(inicio, fim, passo)
```

Segundo a documentação, o `range()` gera uma sequência de números inteiros a partir do valor do parâmetro `inicio` até o valor do parâmetro `fim`, de acordo com o valor do parâmetro `passo`. Se `inicio` não for especificado, o valor padrão é 0. Se `passo` não for especificado, o valor padrão é 1.

Vamos fazer o mesmo contador `while` agora com `for`.
"""

for i in range(1,11):
  print(i)

for i in range(1,4):
  print(f"Aluno {i}")
  nota_1 = float(input('Digite a 1° nota: '))
  nota_2 = float(input('Digite a 2° nota: '))

  print(f'Média: {(nota_1+nota_2)/2}')
print('Fim da repetição')

"""# Estruturas de dados

Um conjunto de elementos é uma coleção de itens, que são armazenados juntos de maneira organizada. Alguns exemplos de conjuntos de elementos em Python são listas, strings e dicionários.

## Listas

As listas podem armazenar uma coleção de itens em ordem. Eles são delimitados por colchetes `[]` e os itens são separados por vírgulas.

Elas também podem armazenar qualquer tipo de item, incluindo números, strings, objetos e outras listas. Elas também podem armazenar itens de tipos de dados diferentes juntos em uma única lista.
"""

lista = ['Fabricio Daniel', 9.5 , 9.0 , 8.0 , True]
lista

"""As listas são organizadas em Python porque **cada elemento da lista tem um índice que indica sua posição na lista**. Os índices começam em 0 e vão até o tamanho da lista menos 1.

Temos então 5 elementos com índices variando de 0 a 4, ordenadamente:

```
#             [0]           [1]   [2]   [3]    [4]
lista = ['Fabricio Daniel', 9.5 , 9.0 , 8.0 , True]
```

Em Python temos também os índices **negativos** que se iniciam no último elemento com o valor de `-1` e depois avancam no universo dos negativos até chegar no 1° elemeno:

```
#             [-5]         [-4]  [-3]  [-2]   [-1]
lista = ['Fabricio Daniel', 9.5 , 9.0 , 8.0 , True]
```

Conseguimos selecionar separadamente cada elemento através de seus respectivos índices. Colocando o nome da lista e em seguida o índice a ser selecionado.
"""

lista[0]

lista[1]

lista[-5]

"""Uma forma mais dinâmica de trabalhar item por item de uma lista é utilizando um laço for para leitura elemento a elemento."""

for i in lista:
  print(i)

"""A nota `8.0` de Fabricio Daniel precisa ser ajustada pois ganhou 2 pontos em sua ultima nota por fazer um trabalho de turma. Então é necessária fazer uma troca no valor do índice `3` de `8.0` para `10.0`."""

lista[3] = 10.0
lista

"""conseguimos calcular a média do aluno a partir dos dados que temos"""

media = (lista[1] + lista[2] + lista[3])/3
media

"""## Manipulação de listas

As listas são muito úteis em Python porque permitem armazenar e acessar uma coleção de itens de maneira organizada e rápida. Elas também oferecem muitos métodos úteis para manipular os itens armazenados, como adicionar, remover, classificar e pesquisar elementos.

#### Quantidade de elementos

Usamos a função [`len()`](https://docs.python.org/3/library/functions.html#len) para descobrimos a quantidade de elementos de um conjunto.
"""

len(lista)

"""#### Partição

A partição de listas por indexação em Python é uma técnica muito útil para selecionar um subconjunto de elementos de uma lista. Ela é feita usando a sintaxe `lista[inicio:fim]`, onde `inicio` é o índice do primeiro elemento a ser incluído na partição e `fim` é o índice do primeiro elemento a ser excluído da partição.
"""

lista[1:4]

lista[1:3]

lista[:4]

lista[3:]

lista[:]

"""#### [`append()`](https://docs.python.org/3/tutorial/datastructures.html#:~:text=of%20list%20objects%3A-,list.append(x),-Add%20an%20item)

Adiciona um elemento ao final da lista.
"""

lista.append(media)
lista

"""#### [`extend()`](https://docs.python.org/3/tutorial/datastructures.html#:~:text=list.extend(iterable))

Adiciona vários elementos ao final da lista.

Adicionaremos as notas `[10.0,8.0,9.0]` na lista do Fabricio Daniel
"""

lista.extend([10.0,8.0,9.0])
lista

"""*Isso não é possivel ser feito com o* `append`."""

lista.append([10.0,8.0,9.0])
lista

"""#### [`remove()`](https://docs.python.org/3/tutorial/datastructures.html#:~:text=append(x).-,list.remove(x),-Remove%20the%20first)

Remove um elemento específico da lista.
"""

lista.remove([10.0,8.0,9.0])
lista

"""## Dicionário

Os dicionários são um tipo de estrutura de dados que armazenam pares de *chave-valor*. Eles são delimitados por chaves `{}` e os pares *chave-valor* são separados por vírgulas.

```
dicionário = {chave: valor}
```

A **chave** é um elemento único que identifica um valor no dicionário, enquanto o **valor** é o item que é armazenado para a chave. As chaves e os valores podem ser de **qualquer tipo de dado**.

Os dicionários são úteis para armazenar e acessar dados de maneira organizada e rápida. Eles são um tipo de conjunto de elementos em Python, pois armazenam uma coleção de itens.
"""

dicionario = {'chave_1':1,
              'chave_2':2}
dicionario

"""---
**Situação:**

Vamos criar um conjunto de dados com informações de matricula de um estudante. Os dados são os seguintes:

- matricula: 2000168933
- dia de cadastro: 25
- mês de cadastro: 10
- turma: 2E
"""

cadastro = {'matricula': 2000168933,
            'dia_cadastro': 25,
            'mes_cadastro': 10,
            'turma': '2E'}
cadastro

cadastro['matricula']

cadastro['turma']

"""É possível substituir os valores dentro de uma chave. Por exemplo, recebemos a informação que a turma do estudante que cadastramos foi trocada para `'2G'` e agora precisamos trocar o valor da chave `'turma'`."""

cadastro['turma'] = '2G'
cadastro

"""Podemos também adicionar outros dados ao dicionário. Vamos adicionar a informação de modalidade de ensino, nosso estudante atuará inicialmente em modalidade EAD.

Então iremos definir uma chave chamada `'modalidade'` e o valor `'EAD'`.
"""

cadastro['modalidade'] = 'EAD'
cadastro

"""## Aprofundando em dicionários

#### [`pop()`](https://python-reference.readthedocs.io/en/latest/docs/dict/pop.html)
Remove um item de um dicionário e o retorna.
"""

cadastro.pop('turma')

cadastro

"""#### [`items()`](https://python-reference.readthedocs.io/en/latest/docs/dict/items.html)
Retorna uma lista de pares chave-valor do dicionário.
"""

cadastro.items()

"""#### [`keys()`](https://python-reference.readthedocs.io/en/latest/docs/dict/keys.html)
Retorna uma lista das chaves do dicionário.
"""

cadastro.keys()

"""#### [`values()`](https://python-reference.readthedocs.io/en/latest/docs/dict/values.html)
Retorna uma lista dos valores do dicionário.
"""

cadastro.values()

"""### Leitura de valores com `for`"""

for i in cadastro.keys():
  print(cadastro[i])

for i in cadastro.values():
  print(i)

for k, v in cadastro.items():
  print(k,v)

"""# **Desafios das Aulas**

"""

# DESAFIO PYTHON PARA DATASCIENCE AULA O2
nomeUsuario = input('Digite seu nome: ')
idadeUsuario = int(input('Digite sua idade: '))
alturaUsuario = float(input('Digite sua altura: '))
print(f"O nome do usuário é {nomeUsuario}, sua idade é {idadeUsuario} anos e sua altura é {alturaUsuario} metros.")

v1 = float(input('digite um valor: '))
v2 = float(input('digite outro valor: '))
print(f'A soma dos valores é {v1+v2}')

v1 = float(input('digite um valor: '))
v2 = float(input('digite outro valor: '))
v3 = float(input('digite mais um valor: '))
print(f'A soma dos valores é {v1+v2+v3}')

v1 = float(input('digite um valor: '))
v2 = float(input('digite outro valor: '))
print(f'A diferença dos valores é {v1-v2}')

v1 = float(input('digite um valor: '))
v2 = float(input('digite outro valor: '))
print(f'O produto dos valores é {v1*v2}')

v1 = float(input('digite um numerador: '))
v2 = float(input('digite um denominador(!= 0): '))
print(f'A razão dos valores é {v1/v2}')

v1 = float(input('digite uma base: '))
v2 = float(input('digite um expoente: '))
print(f'A potencia dos valores é {v1**v2}')

v1 = float(input('digite um numerador: '))
v2 = float(input('digite um denominador(!= 0): '))
print(f'A razão inteira dos valores é {v1//v2}')

v1 = float(input('digite um numerador: '))
v2 = float(input('digite um denominador(!= 0): '))
print(f'O resto da razão dos valores é {v1%v2}')

v1 = float(input('digite sua 1ª nota: '))
v2 = float(input('digite sua 2ª nota: '))
v3 = float(input('digite sua 3ª nota: '))
print(f'A média das notas é: {v1+v2+v3/3}')

media_ponderada = (5*1 + 12*2 + 20*3 + 15*4) / (1+2+3+4)
print(f'Média {media_ponderada}.')

frase = 'Olá Python!'
print(frase)

frase = input('Digite uma frase: ')
print(frase)

frase = input('Digite uma frase: ')
print(frase.upper())

frase = input('Digite uma frase: ')
print(frase.lower())

frase = '   Olá Python!      '
print(frase.strip())

frase = input('Digite uma frase: ')
print(frase.strip())

frase = input('Digite uma frase: ')
print(frase.strip().lower())

frase = input('Digite uma frase: ')
print(frase.lower().replace('e','f'))

frase = input('Digite uma frase: ')
print(frase.lower().replace('a',chr(64)))

frase = input('Digite uma frase: ')
print(frase.lower().replace('s',chr(36)))

n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))

if n1 > n2:
  print(f'{n1} é maior que {n2}')
else:
  print(f'{n2} é maior que {n1}')

porcentagem = float(input('Digite o percentual de crescimento: '))

if porcentagem > 0:
    print(f'Houve um crescimento de {porcentagem}%')
elif porcentagem < 0:
    print(f'Houve um decrescimento de {porcentagem}%')
else:
    print('Não houve crescimento ou decrescimento.')

vogais  = 'a,e,i,o,u'
letra = input('Digite uma letra:').lower()

if letra in vogais:
  print('A letra é vogal')

else:
  print('A letra é consoante')

preco_ano1 = float(input('Informe o preço médio do carro no primeiro ano: '))
preco_ano2 = float(input('Informe o preço médio do carro no segundo ano: '))
preco_ano3 = float(input('Informe o preço médio do carro no terceiro ano: '))

maior = preco_ano1
if preco_ano2 > maior:
  maior = preco_ano2
if preco_ano3 > maior:
  maior = preco_ano3

menor = preco_ano1
if preco_ano2 < menor:
  menor = preco_ano2
if preco_ano3 < menor:
  menor = preco_ano3

print(f'O preço mais alto foi de R$ {maior}.')
print(f'O preço mais baixo foi de R$ {menor}.')

p1 = float(input('Digite o preço do primeiro produto: '))
p2 = float(input('Digite o preço do segundo produto: '))
p3 = float(input('Digite o preço do terceiro produto: '))

if p1 < p2 and p1 < p3:
    print('O primeiro produto é o mais barato.')
elif p2 < p1 and p2 < p3:
    print('O segundo produto é o mais barato.')
elif p3 < p1 and p3 < p2:
    print('O terceiro produto é o mais barato.')
elif p1 == p2 == p3:
    print('Os produtos possuem o mesmo preço.')
else:
    if p1 == p2:
        print('O primeiro e o segundo produtos são os mais baratos.')
    elif p2 == p3:
        print('O segundo e terceiro produtos são os mais baratos.')
    elif p1 == p3:
        print('O primeiro e o terceiro produtos são os mais baratos.')

num1 = int(input('Informe o primeiro número: '))
num2 = int(input('Informe o segundo número: '))
num3 = int(input('Informe o terceiro número: '))

if (num1 >= num2) and (num1 >= num3):
    print(num1)
    if num2 >= num3:
        print(num2)
        print(num3)
    else:
        print(num3)
        print(num2)
elif (num2 >= num1) and (num2 >= num3):
    print(num2)
    if num1 >= num3:
        print(num1)
        print(num3)
    else:
        print(num3)
        print(num1)
else:
    print(num3)
    if num1 >= num2:
        print(num1)
        print(num2)
    else:
        print(num2)
        print(num1)

turno = input('Digite em qual turno você estuda (manhã, tarde ou noite): ')

if turno == 'manhã':
  print('Bom Dia!')
elif turno == 'tarde':
  print('Boa Tarde!')
elif turno == 'noite':
  print('Boa Noite!')
else:
  print('Valor Inválido!')

num = int(input('Digite um número: '))

if (num % 2) == 0:
    print('O número é par.')
else:
    print('O número é ímpar.')

num = float(input('Digite um número: '))

if num % 1 == 0:
    print('O número é inteiro.')
else:
    print('O número é decimal.')

# Coletamos os números a serem operados e solicitamos a operação desejada pela pessoa usuária
num1 = float(input('Informe o primeiro número: '))
num2 = float(input('Informe o segundo número: '))
operacao = input('Informe a operação desejada (+, -, *, /): ')

# Verificamos o operador que foi selecionado e executa a operação matemática conforme a seleção
if operacao == '+':
    resultado = num1 + num2
elif operacao == '-':
    resultado = num1 - num2
elif operacao == '*':
    resultado = num1 * num2
elif operacao == '/':
    resultado = num1 / num2
else: # Especificamos um resultado caso a pessoa usuária não digite alguma das operações corretamente.
    print('Operação inválida, resultado da operação será 0')
    resultado = 0

#  Fazemos as mesmas verificações das questões anteriores para fazer o relatório do cálculo entre números
if resultado % 1 == 0:
    print('O resultado é inteiro.')
else:
    print('O resultado é decimal.')

if resultado > 0:
    print('O resultado é positivo.')
elif resultado == 0:
    print('O resultado é neutro.')
else:
    print('O resultado é negativo.')

if resultado % 2 == 0:
    print('O resultado é par.')
else:
    print('O resultado é ímpar.')

# Coletamos os lados de um triângulo
print('Coletaremos os lados de um triângulo.')
lado1 = float(input('Digite o comprimento do primeiro lado: '))
lado2 = float(input('Digite o comprimento do segundo lado: '))
lado3 = float(input('Digite o comprimento do terceiro lado: '))

# Verificamos de os lados formam um triângulo
if (lado1 + lado2 > lado3) and (lado2 + lado3 > lado1) and (lado1 + lado3 > lado2):
    print('Os valores podem formar um triângulo!')
    # comparamos os lados para verificar o tipo de triângulo
    if (lado1 == lado2) and (lado2 == lado3):
        print('O triângulo é equilátero.')
    elif (lado1 != lado2) and (lado2 != lado3) and (lado1 != lado3):
        print('O triângulo é escaleno.')
    else:
        print('O triângulo é isósceles.')
else:
    print('Os valores não podem formar um triângulo!')

# Coletamos a quantidade de litros e o tipo de combustível,
# já deixando o caractere em maiúsculo para facilitar nossa análise
quantidade_litros = float(input('Informe a quantidade de litros vendidos: '))
tipo_combustivel = input('Informe o tipo de combustível (E para etanol e D para diesel): ').upper()

#  Verificamos primeiro o tipo de combustível
if tipo_combustivel == 'E':
  # Taxamos o valor do preço em litros do etanol
  preco_litro = 1.70
  # De acordo com o valor da quantidade de litros, taxamos também o desconto
  if quantidade_litros <= 15:
    desconto = 0.02
  else:
    desconto = 0.04
elif tipo_combustivel == 'D':
  # Taxamos o valor do preço em litros do disel
  preco_litro = 2.00
  # De acordo com o valor da quantidade de litros, taxamos também o desconto
  if quantidade_litros <= 15:
    desconto = 0.03
  else:
    desconto = 0.05
# Caso ocorra um erro na especificação de tipo de combustível,
# consideramos entradas inválidas, e os preços são taxados em 0
else:
    print('Entradas inválidas!')
    preco_litro = 0
    desconto = 0

# Fazemos o cálculo do valor de desconto, seguido do cálculo do preço descontado
valor_desconto = preco_litro * quantidade_litros * desconto
valor_pago = preco_litro * quantidade_litros - valor_desconto

# Resultado
print(f'Valor a ser pago pelo cliente: R$ {valor_pago}')

# Coletamos as vendas dos dois anos
venda_2022 = float(input('Informe a quantidade de vendas em 2022: '))
venda_2023 = float(input('Informe a quantidade de vendas em 2023: '))

# Calculamos a variação percentual entre as vendas dos anos de 2022 e 2023
var_percentual = 100 * (venda_2023 - venda_2022) / (venda_2022)

# Análise condicional da variação percentual para determinar a sugestão a ser enviada
if var_percentual > 20:
    print('Bonificação para o time de vendas.')
elif 2 <= var_percentual <= 20:
    print('Pequena bonificação para time de vendas.')
elif -10 <= var_percentual < 2:
    print('Planejamento de políticas de incentivo às vendas.')
else:
    print('Corte de gastos.')

# Coletamos os valores de início e fim
inicio = int(input('Insira o primeiro número inteiro: '))
fim = int(input('Insira o segundo número inteiro: '))

# Verificamos se o valor de início é maior que o fim
if inicio < fim:
  # podemos imprimir os inteiros entre o menor e o maior valor
  for i in range(inicio + 1, fim):
    print(i)
elif inicio > fim:
  for i in range(fim + 1, inicio):
    print(i)
else: #caso os números sejam iguais, não conseguimos imprimir sequência alguma
  print('Os números são iguais.')

n1 = int(input('Digite um número: '))
n2 = int(input('Digite outro número: '))

if n1 > n2:
  for i in range(n2+1, n1):
    print(i)
elif n1 < n2:
  for i in range(n1+1, n2):
    print(i)
else:
  print('Os números são iguais.')

coloniA = 4
coloniB = 10

taxA = 0.03
taxB = 0.015

dias = 0

while coloniA <= coloniB:
  coloniA *= 1 + taxA
  coloniB *= 1 + taxB
  dias += 1

print(f'Irá levar {dias} dias para a colônia A ultrapassar a colônia B.')

# laço para pegar as 15 notas
for i in range(15):
  nota = float(input(f'Insira a nota da pessoa usuária {i}: '))

  # verifica se a nota está entre 0 e 5
  # se estiver, o laço rodará ininterruptamente até ser obtido um valor válido
  while (nota < 0) or (nota > 5):
    nota = float(input(f'Nota inválida, insira novamente a nota da pessoa usuária {i}: '))

print('Verificação feita. Todas as notas são válidas')

# coletamos a temperatura
temperatura = float(input('Insira a temperatura em Celsius: '))

# inicializamos uma contadora e soma para a média
contadora = 0
soma = 0

# nosso código executa sempre até o valor de temperatura for igual a -273
while temperatura != -273:
    # a soma é dada com a adição da temperatura à variavel soma
    soma += temperatura
    # contamos a quantidade de valores coletados através da contadora
    contadora += 1
    # coletamos novamente a temperatura
    temperatura = float(input('Insira a temperatura em Celsius: '))

media = soma / contadora

print(f'A média das temperaturas é: {media}')

# Pedir o número
num = int(input('Informe um número inteiro: '))

# Inicializar o cálculo
fatorial = 1

# nosso contador inicializa com o número máximo
# e será feita uma contagem decrescente com o operador -=
i = num
while i > 0:
    # queremos multiplicar agora o valor do fatorial pelo num
    # e todos os números abaixo dele até 1
    fatorial *= i
    i -= 1

# Imprimir o cálculo do fatorial
print(f'Fatorial de {num} é {fatorial}')

# Pedir o número
num = int(input('Informe um número inteiro de 1 a 10: '))

# Vamos gerar a tabuada
print(f'Tabuada do {num}:')
for i in range(1, 11):
    resultado = num * i
    print(f'{num} x {i} = {resultado}')

# Solicitamos o número
num = int(input("Digite o número: "))

# Assumimos que o número é primo até que se prove o contrário
eh_primo = True

# Números abaixo de 2 não são primos
if num <= 1 :
  eh_primo = False
else:
    for i in range(2, num):
        # Se o número for divisível por qualquer número dentro deste intervalo,
        # ele não é primo, portanto, mudamos a variável 'eh_primo' para False e saímos do loop.
        if num % i == 0:
            eh_primo = False
            break

# Verifica se 'eh_primo' ainda é True, o que significa que o número passou pelo loop
# sem ser divisível por nenhum número além de 1 e ele mesmo.
if eh_primo:
    # Se for o caso, o número é primo.
    print(f'O número {num} é primo')
else:
    # Caso contrário, o número não é primo.
    print(f'O número {num} não é primo')

# Coletamos as idades dos clientes
idade = int(input('Informe a idade (ou um número negativo para encerrar): '))

# Inicializamos as variáveis de contadores
contador_0_25 = 0 # contador de idades entre 0 e 25
contador_26_50 = 0 # contador de idades entre 26 e 50
contador_51_75 = 0 # contador de idades entre 51 e 75
contador_76_100 = 0 # contador de idades entre 76 e 100

# nosso código executa sempre até o valor de idade for negativa
while idade >= 0:
    # contamos cada caso
    if idade >= 0 and idade <= 25:
        contador_0_25 += 1
    elif idade >= 26 and idade <= 50:
        contador_26_50 += 1
    elif idade >= 51 and idade <= 75:
        contador_51_75 += 1
    elif idade >= 76 and idade <= 100:
        contador_76_100 += 1

    # Repetir o processo de entrada de dados até que seja digitado um número negativo
    idade = int(input('Informe a idade (ou um número negativo para encerrar): '))

# Mostramos os resultados
print('Distribuição de idades:')
print('[0-25]:', contador_0_25)
print('[26-50]:', contador_26_50)
print('[51-75]:', contador_51_75)
print('[76-100]:', contador_76_100)

# Inicializamos as variáveis contadoras
votos_candidato1 = 0
votos_candidato2 = 0
votos_candidato3 = 0
votos_candidato4 = 0
votos_nulos = 0
votos_branco = 0

# Início do laço para ler os votos
for i in range(0,20):
    voto = int(input('Informe seu voto: '))
    if voto == 1:
        votos_candidato1 += 1
    elif voto == 2:
        votos_candidato2 += 1
    elif voto == 3:
        votos_candidato3 += 1
    elif voto == 4:
        votos_candidato4 += 1
    elif voto == 5:
        votos_nulos += 1
    elif voto == 6:
        votos_branco += 1
    else:
        print("Voto inválido.")

print(f'Votos candidato 1: {votos_candidato1}')
print(f'Votos candidato 2: {votos_candidato2}')
print(f'Votos candidato 3: {votos_candidato3}')
print(f'Votos candidato 4: {votos_candidato4}')
print(f'Votos nulos: {votos_nulos}')
print(f'Votos em branco: {votos_branco}')
print(f'Percentual de votos nulos: {(votos_nulos / 20 * 100)}')
print(f'Percentual de votos em branco: {(votos_branco / 20 * 100)}')

# Dados de gastos
gastos = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]

# Calculamos a média encontrando o valor total de gastos com sum
# e a quantidade total de compras realizadas com len
total_gastos = sum(gastos)
quantidade_compras = len(gastos)
media_gastos = total_gastos / quantidade_compras
# Resultado
print(f'A média de gastos é {media_gastos} reais.')

# Dados de gastos
gastos = [2172.54, 3701.35, 3518.09, 3456.61, 3249.38, 2840.82, 3891.45, 3075.26, 2317.64, 3219.08]

# Variável que vai contar quantas compras foram feitas acima de 3000
contador_acima_3000 = 0
# Usamos o laço para ler a lista de gastos
for gasto in gastos:
  # Verificamos se o elemento está acima de 3000
  if gasto > 3000:
    # Acrescentamos mais um no contador, caso tenha algum valor acima de 3000
    contador_acima_3000 += 1

# Quantidade Compras
# Variável que vai ser utilizada para o cálculo da porcentagem
quantidade_compras = len(gastos)


# Com a contagem conseguimos calcular a porcentagem de valores acima de 3000 entre todas as compras
porcentagem_acima_3000 = 100 * (contador_acima_3000) / (quantidade_compras)

# Resultado
print(f'{contador_acima_3000} compras foram acima de R$3000,00.')
print(f'{porcentagem_acima_3000}% dos gastos foram acima de R$3000,00.')

# Lista que irá armazenar os 5 números inteiros
lista_numeros = []

# Criamos um laço que vai iterar 5 vezes para receber os 5 números
for i in range(0, 5):
  # Coletamos o valor e inserimos na lista por 5 vezes
  numero = int(input('Digite um número inteiro: '))
  lista_numeros.append(numero)
#Resultado
print(f'Lista de números inseridos: {lista_numeros}')

# Lista que irá armazenar os 5 números inteiros
lista_numeros = []

# Criamos um laço que vai iterar 5 vezes para receber os 5 números
for i in range(0, 5):
  # Coletamos o valor e inserimos na lista por 5 vezes
  numero = int(input('Digite um número inteiro: '))
  lista_numeros.append(numero)
# Usamos da lógica de partição para imprimir o resultado
print(f'Lista de números invertida: {lista_numeros[::-1]}')

# Coletamos o números
numero = int(input('Digite um número inteiro: '))
# Lista para receber os números primos
lista_primos = []
# Laço que vai rodar por todos os números abaixo do número digitado
for num in range(2, numero):
  # Primo é uma bandeira, ela permite sabermos se o valor analisado é ou não primo
  primo = True
  # Testamos se todos os números abaixo do especificado no primeiro laço podem
  # gerar uma divisão exata
  for teste_divisiveis in range(2, num):
    if num % teste_divisiveis == 0:
      # Caso seja divisivel por algum número entendemos que
      # o num não é primo e finalizamos o laço interno com break
      primo = False
      break
  # A condição se torna o resultado booleno de primo: False, ignoramos o condicional
  # True, executamos o bloco do if
  if primo:
    lista_primos.append(num)
# Resultado
print(f'Lista de números primos: {lista_primos}')

# Coletamos a data
dia = int(input('Digite o dia: '))
mes = int(input('Digite o mês: '))
ano = int(input('Digite o ano: '))

# Análise de fevereiro
if mes == 2:
  # Verificamos se é ou não um ano bissexto
  if ano % 4 == 0 and (ano % 400 == 0 or ano % 100 != 0):
    dias_fevereiro = 29
  else:
    dias_fevereiro = 28
  # Verificamos se o dia colocado corresponde ao máximo de dias de fevereiro
  if dia >= 1 and dia <= dias_fevereiro:
    print('Data válida')
  else:
    print('Data inválida')
# Verificamos meses terminados em 31 dias
elif mes in [1, 3, 5, 7, 8, 10, 12]:
  if dia >= 1 and dia <= 31:
    print('Data válida')
  else:
    print('Data inválida')
# Verificamos meses terminados em 30 dias
elif mes in [4, 6, 9, 11]:
  if dia >= 1 and dia <= 30:
    print('Data válida')
  else:
    print('Data inválida')
# Caso o mês não esteja entre 1 e 12
else:
  print('Data inválida')

# Lista de crescimento das bactérias
bacterias_colonia = [1.2, 2.1, 3.3, 5.0, 7.8, 11.3, 16.6, 25.1, 37.8, 56.9]
# Lista que irá armazenar as porcentagens de crescimento
porcentagem_crescimento = []
# Vamos percorrer os índices de 1 a 9 para compararmos o valor atual com o passado
for i in range(1, len(bacterias_colonia)):
  # seguimos o cálculo 100 * (amostra_atual - amostra_passada) / (amostra_passada)
  porcentagem = 100 * (bacterias_colonia[i] - bacterias_colonia[i-1]) / (bacterias_colonia[i-1])
  # adicionamos o resultado na lista porcentagem_crescimento
  porcentagem_crescimento.append(porcentagem)
# Resultado
print(f'Porcentagens de crescimento:\n{porcentagem_crescimento}')

# Lista que vai receber os valores de IDs
ids = []
# Variáveis contadoras de doces e amargos
doce = 0
amargo = 0

# Criamos um laço que vai iterar 10 vezes para receber os 10 IDs
for i in range(0,10):
  # Coletamos o ID e adicionamos o id na lista
  ids.append(int(input(f'Digite o {i+1}° ID: ')))

# Ler todos os elementos da lista ids e atribuir à id
for id in ids:
  # Verificamos se os elementos são pares ou ímpares para fazer a contagem
  if id % 2 == 0:
    doce += 1
  else:
    amargo += 1

# Resultado
print(f'Quantidade de produtos doces: {doce}')
print(f'Quantidade de produtos amargos: {amargo}')

# Inicializamos os dados
respostas = [] # Lista para receber as respostas
# Lista de gabaritos
gabarito = ['D', 'A', 'C', 'B', 'A', 'D', 'C', 'C', 'A', 'B']
nota = 0 # Irá acumular a nota total

# Recebemos as respostas do aluno
for i in range(0, 10):
  respostas.append(input(f'Insira a resposta da questão {i + 1}: ').upper())

# Verificamos se as respostas são iguais e adicionamos à nota
for i in range(0,10):
  if respostas[i] == gabarito[i]:
    nota += 1

# Exibindo nota final
print(f'Nota final: {nota}')

# Coletamos a lista de temperaturas
temperaturas_mensais = []
for i in range(0,12):
  temperaturas_mensais.append(float(input(f'Digite a média de temperatura do mês {i+1}: ')))
# Criamos uma lista auxiliar para os nomes dos meses
meses = ['Janeiro', 'Fevereiro', 'Março', 'Abril', 'Maio', 'Junho', 'Julho', 'Agosto', 'Setembro', 'Outubro', 'Novembro', 'Dezembro']
# Calculamos a média
media_anual = sum(temperaturas_mensais) / len(temperaturas_mensais)

#Resultado
print('Temperaturas acima da média em: ')
for i in range(0,12):
  # Verificamos todas as temperaturas de acordo com a média anual
  if temperaturas_mensais[i] > media_anual:
    # Como os índices dos meses correspondem às temperaturas,
    # podemos imprimir eles sob o mesmo índice
    print(meses[i])

# Dicionário de vendas
dados_vendas = {'Produto A': 300, 'Produto B': 80, 'Produto C': 60, 'Produto D': 200, 'Produto E': 250, 'Produto F': 30}

# Inicializamos as variáveis
total_vendas = 0 # Irá somar todos as vendas
produto_mais_vendido = '' # Irá armazenar o nome do produto mais vendido
unidades_produto_mais_vendido = 0 # Irá armazenar a maior quantidade vendas

# Percorremos os valores de chaves e elementos do dicionário
for produto in dados_vendas.keys():
  # Somamos o total de vendas
  total_vendas += dados_vendas[produto]
  # Verificamos se valor de venda atual desing (dados_vendas[produto]) é maior que o valor armazenado em unidades_produto_mais_vendido
  # Cada vez que dados_vendas[produto] superar o valor em unidades_produto_mais_vendido,
  # a variável unidades_produto_mais_vendido vai ser igual à dados_vendas[produto], atribuindo um novo valor
  # De forma similar, produto_mais_vendido também é substituído pelo produto atual
  if dados_vendas[produto] > unidades_produto_mais_vendido:
    unidades_produto_mais_vendido = dados_vendas[produto]
    produto_mais_vendido = produto
# Resultados
print(f'Total de vendas é {total_vendas}')
print(f'{produto_mais_vendido} é o mais vendido')

# Dicionário de votos por design
votos = {'Design 1': 1334, 'Design 2': 982, 'Design 3': 1751, 'Design 4': 210, 'Design 5': 1811}

# Inicializamos as variáveis
total_votos = 0 # Irá somar todos os votos
vencedor = '' # Irá armazenar o nome do design vencedor
voto_vencedor = 0 # Irá armazenar a quantidade vencedora de votos

# Percorremos os valores de chaves e elementos do dicionário
for design, voto_desing in votos.items():
  # Somamos o total de votos
  total_votos += voto_desing
  # Verificamos se o voto do atual desing (voto_desing) é maior que o valor armazenado em voto_vencedor
  # Cada vez que voto_desing superar o valor em voto_vencedor,
  # a variável voto_vencedor vai ser igual à voto_desing, atribuindo um novo valor
  # De forma similar, o vencedor também é substituído pelo design
  if voto_desing > voto_vencedor:
    voto_vencedor = voto_desing
    vencedor = design
# Calculamos a porcentagem do design vencedor
porcentagem = 100 * (voto_vencedor) / (total_votos)

#Resultado
print(f'{vencedor} é o vencedor: ')
print(f'Porcentagem de votos: {porcentagem}%')

# Lista de salários
salarios = [1172, 1644, 2617, 5130, 5532, 6341, 6650, 7238, 7685, 7782, 7903]
# Inicializamos as variáveis
dic_abonos = {} # Dicionário de abonos
total_abono = 0 # Irá somar todos os gastos com abono
abonos_minimo = 0 # Irá armazenar a quantidade de abonos mínimos
maior_abono = 0 # Irá armazenar o maior valor de abono

# Percorremos toda a lista de salários
for salario in salarios:
  # Calculamos o valor teórico de abono
  abono = salario * 0.1
  # Caso o abono seja inferior a 200,
  # ajustamos o valor de abono para o mínimo (200)
  if abono < 200:
    abono = 200
  # Adicionamos um novo dado no dicionário chave abono
  dic_abonos[salario] = abono

# Percorremos todos os valores do dicionário de abonos
for abono in dic_abonos.values():
  # Contamos o salário minimo
  if abono == 200:
    abonos_minimo += 1
  # Verificamos se o abono lido é maior que o valor armazenado em maior_abono
  # Cada vez que o abono superar o valor de maior_abono,
  # a variável maior_abono vai ser igual à abono, atribuindo um novo valor
  if abono > maior_abono:
    maior_abono = abono
  # Somamos os abonos
  total_abono += abono
# Resultados
print(f'Abonos: {dic_abonos}')
print(f'Total de gasto com abonos: {total_abono}')
print(f'Número de funcionários que receberam o abono mínimo: {abonos_minimo}')
print(f'Maior valor de abono: {maior_abono}')

# Especificamos os dados para um dicionário
dados = {'Área Norte': [2819, 7236],
         'Área Leste': [1440, 9492],
         'Área Sul': [5969, 7496],
         'Área Oeste': [14446, 49688],
         'Área Centro': [22558, 45148]}
# Inicializamos as variáveis
soma_media = 0 # Irá somar todas as médias
maior_diversidade = '' # Irá armazenar a área com maior diversidade
maior_soma = 0 # Irá armazenar a maior soma de espécies
# Percorremos os valores de chaves e elementos do dicionário
for area, especies in dados.items():
  # Fazemos a soma do números de espécies em cada área com a função sum
  soma_especies = sum(especies)
  # Calculamos a média dividindo a soma das espécies pela quantidade de espécies
  media = soma_especies / len(especies)
  # Imprimimos
  print(f'A {area} tem a média de {media} espécies')
  # Verificamos se a soma das espécies é maior que o valor armazenado de maior_soma
  # Cada vez que a soma_especies superar o valor de maior_soma,
  # a variável maior_soma vai ser igual à soma_especies, atribuindo um novo valor
  # De forma similar, maior_diversidade também é substituída
  if soma_especies > maior_soma:
      maior_soma = soma_especies
      maior_diversidade = area
  # Somamos as médias
  soma_media += media
# A média total será dada pela soma_media dividida pela quantidade de áreas
media_total = soma_media / len(dados)
print(f'Média geral de espécies: {media_total}')
print(f'Área com a maior diversidade biológica: {maior_diversidade}')

# Especificamos os dados para um dicionário
dados = {'Setor A': [22, 26, 30, 30, 35, 38, 40, 56, 57, 65],
        'Setor B': [22, 24, 26, 33, 41, 49, 50, 54, 60, 64],
        'Setor C': [23, 26, 26, 29, 34, 35, 36, 41, 52, 56],
        'Setor D': [19, 20, 25, 27, 34, 39, 42, 44, 50, 65]}
# Inicializamos a variável que irá somar todas as idades
total_idades = 0
# Percorremos os valores de chaves e elementos do dicionário
for setor, idades in dados.items():
  # Calculamos a média dividindo a soma das idades pela quantidade funcionários em cada setor
  media_idade = sum(idades) / len(idades)
  # Imprimimos
  print(f'O {setor} tem a média de {media_idade}')
  # Somamos as médias
  total_idades += sum(idades)
# A média total será dada pela total_idades dividida pela quantidade de pessoas totais (setores * funcionários por setor)
media_total = total_idades / (len(idades) * len(dados))
print(f'A média de idade geral é {media_total}')

# Inicializamos a variável que irá contar todas pessoas com idade acima da média
acima_media = 0
# Percorremos novamente os valores de chaves e elementos do dicionário
for setor, idades in dados.items():
  # Lemos os elementos (idades) dentro de cada lista de idades no dicionário
  for id in idades:
    # Verificamos se o valor da idade é superior à média total
    if id > media_total:
      # Caso o valor da idade seja superior à média, incrementamos mais um no contador
      acima_media += 1
# Resultado
print(f'{acima_media} pessoas estão acima da idade média geral')

#LOUCURA ISSO AQUI TÁ